default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.7
    hooks:
    -   id: ruff
        args:
        - --fix
        - --exit-non-zero-on-fix
    -   id: ruff-format
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
