name: final-work


services:
  airflow:
    image: docker.io/bitnami/airflow:2
    container_name: airflow
    environment:
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
    env_file:
      - ../.env
    volumes:
      - ../src/dags:/opt/bitnami/airflow/dags
      - ../requirements.txt:/bitnami/python/requirements.txt
    ports:
      - 8080:8080

  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
    env_file:
      - ../.env
    volumes:
      - ../src/dags:/opt/bitnami/airflow/dags
      - ../requirements.txt:/bitnami/python/requirements.txt

  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
    env_file:
      - ../.env
    volumes:
      - ../src/dags:/opt/bitnami/airflow/dags
      - ../requirements.txt:/bitnami/python/requirements.txt

  postgresql:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # only for development !!!
    env_file:
      - ../.env

  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - redis_data:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # only for development !!!

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
